using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace DXApplication2
{
    public partial class main : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public main()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource
            excelDataSource1.Fill();
        }


        /// <summary>
        /// 사업실적등록 클릭 : 클릭시 Hidden상태면, visible로 변경 후 activate한다. (show) , visible이면 hidden 으로 변경 한다(hide()).
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void performanceCreate_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (dockPanel1.Visibility == DevExpress.XtraBars.Docking.DockVisibility.Hidden)
            {
                dockPanel1.Show();
            }
            else
            {
                dockPanel1.Hide();
            }

            // Not use - 기존 새 폼으로 띄어주고있는 내용
            //사업실적등록 newForm = new 사업실적등록();
            //newForm.Owner = this;
            //newForm.Show();

            ////모달창으로 열기
            //subForm.Owner = this;
            //subForm.ShowDialog();
        }

        private void ribbonControl1_Click(object sender, EventArgs e)
        {

        }

        private void performanceReport_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            실적보고서 newForm = new 실적보고서();
            newForm.Owner = this;
            newForm.Show();
        }

        private void barButtonItem5_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }

        private void barListItem1_ListItemClick(object sender, DevExpress.XtraBars.ListItemClickEventArgs e)
        {

        }

        private void backstageViewControl1_Click(object sender, EventArgs e)
        {

        }

        private void backstageViewButtonItem1_ItemClick(object sender, DevExpress.XtraBars.Ribbon.BackstageViewItemEventArgs e)
        {

        }

        private void barWorkspaceMenuItem1_ListItemClick(object sender, DevExpress.XtraBars.ListItemClickEventArgs e)
        {

        }

        private void 메인화면_Load(object sender, EventArgs e)
        {

        }

        private void changepassword_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Settings.Changepassword newForm = new Settings.Changepassword();
            newForm.Owner = this;
            newForm.Show();


        }

        private void 시스템_DB경로설정_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Settings.DBPathSetting newForm = new Settings.DBPathSetting();
            newForm.Owner = this;
            newForm.Show();
        }

        private void setting_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            //Settings.DBPathSetting newForm = new Settings.DBPathSetting();
            //newForm.Owner = this;
            //newForm.Show();
        }

        private void dockPanel2_Click(object sender, EventArgs e)
        {

        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {

        }
    }
}
